---

- name: Installing docker dependency
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: yes

- name: Adding docker apt-key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Removing old arch docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: absent

- name: Adding docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: Installing docker-ce with apt
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present
    update_cache: yes

- name: Making sure /etc/docker is present on machine
  file:
    name: /etc/docker
    state: directory

- name: Making sure docker configuration is present on machine
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: restart docker

- name: starting and enabling docker
  systemd:
    name: docker
    state: started
    enabled: yes
