---

- name: Installing apt-transport-https
  apt:
    name: "apt-transport-https"
    state: latest

- name: Installing docker dependency
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - ca-certificates
    - curl
    - software-properties-common

- name: Adding docker apt-key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Removing old arch docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: absent

- name: Adding docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Installing docker-ce with apt
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present
    update_cache: yes

- name: Making sure /etc/docker is present on machine
  file:
    name: /etc/docker
    state: directory

- name: Making sure docker configuration is present on machine (with devicemapper)
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: restart docker

- name: starting and enabling docker
  systemd:
    name: docker
    state: started
    enabled: yes
