kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testing-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: testing-pvc
  labels:
    app: testing-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-pvc
  template:
    metadata:
      name: testing-pvc
      labels:
        app: testing-pvc
    spec:
      containers:
      - name: alpine
        image: alpine:3.8
        volumeMounts:
        - name: db
          mountPath: "/var/lib/data"
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: testing-pvc
