---

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  listen: restart docker

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
  listen: restart journald

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
  listen: restart kubelet
