---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-a
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: eu-west-1a
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-b
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: eu-west-1b
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-c
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: eu-west-1c
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: eu-west-1a,eu-west-1b,eu-west-1c
