apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: weave-net
  name: weave-net
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: metrics
  - interval: 15s
    port: metrics-npc
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: weave-net
