# - name: getting etcd and role dependencies
#   apt:
#     name:
#       - tar
#       - git
#       - curl
#     state: present

- name: Installing and configuring etcd
  import_tasks: install.yml

- name: Generating TLS certificates
  import_tasks: tls.yml

- name: Enabling and starting ETCD
  systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: started
