---

- name: install nginx
  package:
    name: nginx
    state: present

- name: install nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/etcd.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload NGINX

- name: ensure nginx default sites are disabled
  file:
    path: "/etc/nginx/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - default
    - default-ssl
  notify: Reload NGINX
