---

- name: stopping etcd
  service:
    name: etcd
    state: stopped
  ignore_errors: yes

- name: unlink new CA and certs
  file:
    path: "{{ etcd_certs_dir }}/{{ item[0] }}{{ item[1] }}"
    state: absent
  with_nested:
    - [ 'ca', 'etcdctl-client', 'apiserver-client', 'peer', 'server' ]
    - [ '.pem', '-key.pem' ]

- name: Restoring etcd CA
  copy:
    src: "{{ item }}"
    dest: "{{ etcd_certs_dir }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ etcd_restore_pki_local_files }}"
  when: etcd_secure

- name: removing etcd old data directory
  file:
    path: "{{ etcd_data_dir }}"
    state: absent

- name: Ensuring backup directory exists
  file:
    path: "{{ etcd_backup_dir }}"
    state: directory

- name: uploading etcd snapshot
  copy:
    src: "{{ etcd_restore_snapshot_local_file }}"
    dest: "{{ etcd_restore_snapshot_remote_file }}"
    owner: root
    group: root
    mode: 0640

- name: restoring etcd from snapshot
  command: "etcdctl snapshot restore --data-dir={{ etcd_data_dir | quote }} {{ etcd_restore_snapshot_remote_file | quote }}"
  environment:
    ETCDCTL_API: 3
  notify: Reload ETCD

- name: cleanup after etcd restore
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ etcd_restore_snapshot_remote_file }}"
