---

- name: Generating etcd certificates (server, peer, client)
  shell: "kubeadm alpha phase certs etcd-{{ item }} --cert-dir {{ etcd_certs_dir }}"
  args:
    creates: "{{ etcd_certs_dir }}/etcd/{{ item }}.key"
  with_items:
    - healthcheck-client
    - peer
    - server
