---
etcd_version: v3.3.10
etcd_download_url: https://storage.googleapis.com/etcd
etcd_data_dir: /var/lib/etcd
etcd_binary_dir: /usr/local/bin
etcd_backup: true
etcd_backup_dir: /var/backups/etcd
etcd_backup_retention_days: 1
etcd_config_dir: /etc/etcd
etcd_certs_dir: /etc/etcd/pki/
etcd_certs_local_dir: "."
etcd_secure: true
etcd_metrics: true
etcd_metrics_port: 2378
etcd_restore: false
etcd_restore_snapshot_local_file: "local/current-backup.db"
etcd_restore_snapshot_remote_file: "{{ etcd_backup_dir }}/snapshot.db"
etcd_restore_pki_local_files:
  - local/ca.pem
  - local/ca-key.pem
