apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
spec:
  replicas: 1
  selector:
      matchLabels:
        app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccount: dex
      containers:
      - image: quay.io/dexidp/dex:v2.14.0
        readinessProbe:
            httpGet:
              path: "/healthz"
              port: 5556
        name: dex
        command: 
          - /usr/local/bin/dex
          - serve
          - /etc/dex/cfg/config.yml
        ports:
        - name: http
          containerPort: 5556
        - name: metrics
          containerPort: 5558
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 200Mi
      volumes:
      - name: config
        secret:
          secretName: dex
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  labels:
    app: dex
spec:
  ports:
  - name: http
    port: 5556
    protocol: TCP
  - name: metrics
    port: 5558
    protocol: TCP
  selector:
    app: dex
