---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-janitor
  labels:
    app: kube-janitor
spec:
  schedule: "16 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-janitor
          restartPolicy: Never
          containers:
          - name: kube-janitor
            image: "themagicalkarp/kube-janitor:v0.1.0"
            imagePullPolicy: Always
            command:
              - "/kube-janitor"
              - "-expiration=2880"
              - "-annotation=kube.janitor.io"
              - "-pendingJobExpiration=60"
              - "-verbose"
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
