---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-janitor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-janitor
rules:
- apiGroups: 
  - batch
  - ""
  resources: 
  - jobs
  - pods
  verbs: 
  - get
  - list
  - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-janitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-janitor
subjects:
- kind: ServiceAccount
  name: kube-janitor
